### ISSUE TITLE
API link in TaskService doesn't go anywhere

### ISSUE THREAD

**Issue by danroth27** [AzureADQuickStarts/B2C-WebAPI-DotNet#11]
The API link in the TaskService layout goes to a non existent Help controller.

**Comment by nrogoff** [comment]
Yes also spotted that!

**Comment by gsacavdm** [comment]
@danroth27, @nrogoff, I'm closing this issue since this sample has been deprecated in place of the newer [**Azure AD B2C: Call a .NET web API from a .NET web app** sample](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi). Feel free to submit issues against that one.
