### ISSUE TITLE
Couldn't run the app initially

### ISSUE THREAD

**Issue by dneimke** [AzureADQuickStarts/B2C-WebAPI-DotNet#2]
I pulled latest from GitHub and followed the instructions.  After strarting the Client and API applciations, 

I browsed to either SignUp, SignIn, or Claims in the Client App, I got the following error message:

```
IDX10803: Unable to create to obtain configuration from: 'https://login.microsoftonline.com/DazsMicroApps.onmicrosoft.com/v2.0/.well-known/openid-configuration'. 
```

I tried it a few more times without changing any settings and it worked!

**Comment by dstrockis** [comment]
Hm, that's pretty strange.  Perhaps there was some replication delay between creating your tenant & standing up a valid configuration endpoint. Glad it worked for you.
