### ISSUE TITLE
Not able to load Sign In / Sign Up in Popup window.

### ISSUE THREAD

**Issue by Sivalingaamorthy** [AzureADQuickStarts/B2C-WebAPI-DotNet#3]
I want to load the sign up or sign in page in popup (kendo window) or on div. I tried to do this but the page is not getting loaded, it displays a blank page. What is wrong with this approach ? Is there any limitations ?

**Comment by dstrockis** [comment]
Yes we specifically deny our login pages being iframed, in order to prevent clickjacking.
