### ISSUE TITLE
JWT validation failed. Unable to resolve SecurityKeyIdentifier

### ISSUE THREAD

**Issue by neerajyadav** [AzureADQuickStarts/B2C-WebAPI-DotNet#5]
Environment:
- Web Api 2
- Azure Active directory B2C
- Deployed on Azure API app

Web Api is protected with azure active directory B2C and is deployed on azure API app. It works fine, however sometimes api app start returning 500 - The request timed out.
Few hours later or re-starting the server, api app starts responding again. It happens only with Authorize endpoints.

After hours of logging and analysis I found that it is Azure AD that is causing the problem. Here is the server log.

> 2016-06-20T10:02:54  PID[3872] Warning     JWT validation failed: IDX10500: c. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
>     (
>     IsReadOnly = False,
>     Count = 1,
>     Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
>     )
> ', 
> token: '{"typ":"JWT","alg":"RS256","kid":"IdTokenSigningKeyContainer.v2"}.{"exp":1466420186,"nbf":1466416586,"ver":"1.0","iss":"https://login.microsoftonline.com/47e7d095-0860-410b-a9df-ed6992458ba0/v2.0/","acr":"b2c_1_peoplesignin","sub":"Not supported currently. Use oid claim.","aud":"953584ba-f0da-4cd7-aa95-2274b673061f","nonce":"defaultNonce","iat":1466416586,"auth_time":1466416586,"oid":"9e44b22e-558c-4286-a4c7-e742c03687dc","name":"Neeraj Kumar","emails":["Er.neerajyadav@gmail.com"]}

Here is the ConfigureAuth() method of web api.

``` cs
private void ConfigureAuth(IAppBuilder app)
        {
            TokenValidationParameters tvps = new TokenValidationParameters
            {
                // This is where you specify that your API only accepts tokens from its own clients
                ValidAudience = clientId,
            };

            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
            {
                // This SecurityTokenProvider fetches the Azure AD B2C metadata & signing keys from the OpenIDConnect metadata endpoint
                AccessTokenFormat = new JwtFormat(tvps, new OpenIdConnectCachingSecurityTokenProvider(String.Format(aadInstance, tenant, "v2.0", discoverySuffix, commonPolicy))),

                Provider = new OAuthBearerAuthenticationProvider()
                {
                    OnValidateIdentity = async (context) =>
                    {
                        string userObjectId = context.Ticket.Identity.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
                        var graphClient = new ADGraphClient();
                        var roles = await graphClient.GetUsersGroups(userObjectId);

                        // add a role claim for every membership found
                        foreach (var r in roles)
                            context.Ticket.Identity.AddClaim(new Claim(ClaimTypes.Role, r.ToString()));
                    }  
                }
            });
        }
```

**Comment by dstrockis** [comment]
Hi @neerajyadav, any chance you could get a stack trace for this? `IDX10500` usually means the middleware can't retrieve the signing tokens for validating the token signature.  The retrieval & caching of the signing tokens is handled by the `ConfigurationManager` class, in the `Microsoft.IdentityModel.Protocols` assembly.

Could you also let us know what version of this package you have installed?

`<package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.202250711" targetFramework="net45" />`

If others have hit this error I'd like to know.

**Comment by neerajyadav** [comment]
@dstrockis I can not get the stack trace for this. On my local machine it is working fine and I never faced this issue. This issue arise on azure hosted api app. Restarting the api app solves the problem.

Another thing I came to know is, even in case of successful api calls this `IDX10500` is coming. This warning is coming in every api request which has authorize header. However sometimes server stops the thread execution after this warning and there is no response return to the client, which in turn becomes request time out. Restarting the server resolves the issue again.
Here is the server log I captured.

```
2016-06-20T10:02:44  Welcome, you are now connected to log-streaming service.
2016-06-20T10:02:54  PID[3872] Verbose Received request: GET https://abc.azurewebsites.net/user/claims
2016-06-20T10:02:54  PID[3872] Warning JWT validation failed: IDX10500: c. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 1,
    Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
    )
', 
token: '{"typ":"JWT","alg":"RS256","kid":"IdTokenSigningKeyContainer.v2"}.{"exp":1466420186,"nbf":1466416586,"ver":"1.0","iss":"https://login.microsoftonline.com/47e7d095-0860-410b-a9df-ed6992458ba0/v2.0/","acr":"b2c_1_peoplesignin","sub":"Not supported currently. Use oid claim.","aud":"953584ba-f0da-4cd7-aa95-2274b673061f","nonce":"defaultNonce","iat":1466416586,"auth_time":1466416586,"oid":"9e44b22e-558c-4286-a4c7-e742c03687dc","name":"Neeraj Kumar","emails":["Er.neerajyadav@gmail.com"]}
RawData: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IklkVG9rZW5TaWduaW5nS2V5Q29udGFpbmVyLnYyIn0.eyJleHAiOjE0NjY0MjAxODYsIm5iZiI6MTQ2NjQxNjU4NiwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tLzQ3ZTdkMDk1LTA..........'..

2016-06-20T10:03:29  PID[3872] Information Request, Method=GET, Url=https://abc.azurewebsites.net/apihealth/availability, Message='https://abc.azurewebsites.net/apihealth/availability'
2016-06-20T10:03:29  PID[3872] Information Message='ApiHealth', Operation=DefaultHttpControllerSelector.SelectController
2016-06-20T10:03:29  PID[3872] Information Message='Abc.Api.ResourceServer.Controllers.ApiHealthController', Operation=DefaultHttpControllerActivator.Create
2016-06-20T10:03:29  PID[3872] Information Message='Abc.Api.ResourceServer.Controllers.ApiHealthController', Operation=HttpControllerDescriptor.CreateController
2016-06-20T10:03:29  PID[3872] Information Message='Selected action 'Availability()'', Operation=ApiControllerActionSelector.SelectAction
2016-06-20T10:03:29  PID[3872] Information Operation=HttpActionBinding.ExecuteBindingAsync
2016-06-20T10:03:29  PID[3872] Information Message='Action returned 'System.Web.Http.Results.OkResult'', Operation=ReflectedHttpActionDescriptor.ExecuteAsync
2016-06-20T10:03:29  PID[3872] Information Operation=ApiControllerActionInvoker.InvokeActionAsync, Status=200 (OK)
2016-06-20T10:03:29  PID[3872] Information Operation=ApiHealthController.ExecuteAsync, Status=200 (OK)
2016-06-20T10:03:29  PID[3872] Information Operation=EnforceHttpsHandler.SendAsync, Status=200 (OK)
2016-06-20T10:03:29  PID[3872] Information Response, Status=200 (OK), Method=GET, Url=https://abc.azurewebsites.net/apihealth/availability, Message='Content-type='none', content-length=unknown'
2016-06-20T10:03:29  PID[3872] Information Operation=ApiHealthController.Dispose
2016-06-20T10:03:29  PID[3872] Verbose     Received request: GET https://abc.azurewebsites.net/apihealth/availability

```

As you can see in log, 
- server first receives the `user/claims` request which is an authorized endpoint. 
- It looks up for token validation.
- Server got the warning. `IDX10500`
- **Execution of the thread is stopped by server. and receives another requests `health/availability`**. This is a public endpoint with no authorization. server process the request and returns the response. 
- No further processing was done for `user/claims` request and client get time out after sometime.

Here is the package version.

`<package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.206221351" targetFramework="net46" />`

**Comment by dstrockis** [comment]
Hey @neerajyadav I believe the issue here is actually the one you're facing: https://github.com/AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet/issues/2.  We're trying to come up with a fix.

**Comment by dstrockis** [comment]
If you agree, please close out this issue at duplicate.

**Comment by neerajyadav** [comment]
Duplicate of https://github.com/AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet/issues/2
