### ISSUE TITLE
Refresh tokens in the web api

### ISSUE THREAD

**Issue by ghost** [AzureADQuickStarts/B2C-WebAPI-DotNet#8]
Hi Guys

Do you have any examples on how to manage the refreshing of an access token by using a refresh token in the web api?   My team have been trying for a few days and I would love to know how we could get this going. 

Many Thanks

Gavin

**Comment by gsacavdm** [comment]
@fir3pho3nixx, I'm closing this issue since this sample has been deprecated in place of the newer [**Azure AD B2C: Call a .NET web API from a .NET web app** sample](https://github.com/Azure-Samples/active-directory-b2c-dotnet-webapp-and-webapi). Feel free to submit issues against that one.
